STOP SLAVE;
RESET MASTER;
RESET SLAVE;
RESET SLAVE ALL;
SET GLOBAL gtid_slave_pos = '';
CHANGE MASTER TO MASTER_HOST='server1', MASTER_PORT=3306, MASTER_USER='maxuser', MASTER_PASSWORD='password', MASTER_USE_GTID=slave_pos;
START SLAVE;
